//
//  DetalhesPresenter.swift
//  Mobile2You
//
//  Created by Julio Cezar de Souza on 06/11/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetalhesPresentationLogic
{
  func presentSomething(response: Detalhes.Something.Response)
}

class DetalhesPresenter: DetalhesPresentationLogic
{
  weak var viewController: DetalhesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Detalhes.Something.Response)
  {
    let viewModel = Detalhes.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
